name: InfluxDB V3 Data Sink
language: python
variables:
  - name: INFLUXDB_TAG_COLUMNS
    inputType: FreeText
    description: 'A dictonary containing tags and their expected values. E.g {"room": "Kitchen", "sensor": "K001"}'
    defaultValue: '{}'
    required: false
  - name: INFLUXDB_MEASUREMENT_NAME
    inputType: FreeText
    description: ''
    defaultValue: 100ms_activations
    required: true
  - name: INFLUXDB_HOST
    inputType: FreeText
    description: ''
    defaultValue: https://us-east-1-1.aws.cloud2.influxdata.com
    required: true
  - name: INFLUXDB_ORG
    inputType: FreeText
    description: ''
    defaultValue: ContentSquad
    required: true
  - name: INFLUXDB_DATABASE
    inputType: FreeText
    description: ''
    defaultValue: connector-testing-sink
    required: true
  - name: input
    inputType: InputTopic
    description: ''
    defaultValue: activations-100ms-interval
    required: true
  - name: INFLUXDB_TOKEN
    inputType: Secret
    description: ''
    defaultValue: influx_db3
    required: true
  - name: field_keys
    inputType: FreeText
    description: ''
    defaultValue: "['activation']"
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
