name: InfluxDB V3 Data Source
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: water-temp-30min-samples
    required: true
  - name: INFLUXDB_ORG
    inputType: FreeText
    description: ''
    defaultValue: ContentSquad
    required: true
  - name: INFLUXDB_HOST
    inputType: FreeText
    description: ''
    defaultValue: https://us-east-1-1.aws.cloud2.influxdata.com/
    required: true
  - name: INFLUXDB_MEASUREMENT_NAME
    inputType: FreeText
    description: ''
    defaultValue: h2o_temperature
    required: true
  - name: task_interval
    inputType: FreeText
    description: ''
    defaultValue: 5m
    required: false
  - name: INFLUXDB_DATABASE
    inputType: FreeText
    description: ''
    defaultValue: noaa-water-sample
    required: true
  - name: INFLUXDB_TOKEN
    inputType: Secret
    description: ''
    defaultValue: influx_db3
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
